version: '3.7'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: always
    hostname: PlexServer
    platform: linux/arm/v7
    volumes:
      - ./config:/config
      - /Volumes/4TB2/plex:/mnt/disk0/plex:ro
      - ./transcode:/transcode
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ
      - ADVERTISE_IP
      - PLEX_CLAIM

volumes:
  config: {}
  media: {}
  transcode: {}
