version: '3.7'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - ./config:/config
      - ./media:/data:ro
      - ./transcode:/transcode
    ports:
      - $PLEX_PORT:32400/tcp
    environment:
      - TZ
      - ADVERTISE_IP
    # devices:
    #   - /dev/dri:/dev/dri
    restart:
      always

volumes:
  config: {}
  media: {}
  transcode: {}