version: '3.7'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    hostname: PlexServer
    volumes:
      - ./config:/config
      - ./media:/data:ro
      - ./transcode:/transcode
    ports:
      - "$PLEX_PORT:32400/tcp"
    environment:
      - TZ
      - ADVERTISE_IP
      - PLEX_CLAIM
    privileged: true
    # devices:
    #   - /dev/dri:/dev/dri

volumes:
  config: {}
  media: {}
  transcode: {}